export default {
    ADD_ITEM_INTO_BASKET: 'ADD_ITEM_INTO_BASKET',
    REMOVE_ITEM_INTO_BASKET: 'REMOVE_ITEM_INTO_BASKET',
    EDIT_OWNER: 'EDIT_OWNER',

    // Async
    FETCH_TOP_SALES_LOADING: 'FETCH_TOP_SALES_LOADING',
    FETCH_TOP_SALES_SUCCESS: 'FETCH_TOP_SALES_SUCCESS',
    FETCH_TOP_SALES_FAILURE: 'FETCH_TOP_SALES_FAILURE',

    FETCH_ITEMS_LOADING: 'FETCH_ITEMS_LOADING',
    FETCH_ITEMS_SUCCESS: 'FETCH_ITEMS_SUCCESS',
    FETCH_ITEMS_FAILURE: 'FETCH_ITEMS_FAILURE',

    FETCH_ITEMS_BY_ID_LOADING: 'FETCH_ITEMS_BY_ID_LOADING',
    FETCH_ITEMS_BY_ID_SUCCESS: 'FETCH_ITEMS_BY_ID_SUCCESS',
    FETCH_ITEMS_BY_ID_FAILURE: 'FETCH_ITEMS_BY_ID_FAILURE',

    FETCH_CATEGORIES_LOADING: 'FETCH_CATEGORIES_LOADING',
    FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    FETCH_CATEGORIES_FAILURE: 'FETCH_CATEGORIES_FAILURE',

    ORDER_LOADING: 'ORDER_LOADING',
    ORDER_SUCCESS: 'ORDER_SUCCESS',
    ORDER_FAILURE: 'ORDER_FAILURE',
};
