export {
    ADD_ITEM_INTO_BASKET,
    REMOVE_ITEM_INTO_BASKET,
    INITIAL_BASKET,
    RESET_BASKET,
    RESET_ERRORS,
    EDIT_OWNER,
    CHANGE_QUERY_TEXT,
    FETCH_TOP_SALES_LOADING,
    FETCH_TOP_SALES_SUCCESS,
    FETCH_TOP_SALES_FAILURE,
    FETCH_ITEMS,
    FETCH_MORE_ITEMS,
    MAKE_ORDER,
} from './types';

export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';

// Common
export const SERVER_URL = 'http://localhost:7070/api';
