export {
    ADD_ITEM_INTO_BASKET,
    REMOVE_ITEM_INTO_BASKET,
    INITIAL_BASKET,
    RESET_BASKET,
    RESET_ERRORS,
    EDIT_OWNER,
    CHANGE_QUERY_TEXT,
    FETCH_ITEMS,
    FETCH_MORE_ITEMS,
    MAKE_ORDER,
    FETCH_TOP_SALES,
    FETCH_CATEGORIES,
} from './types';

// Common
export const SERVER_URL = 'http://localhost:7070/api';
