export const ADD_ITEM_INTO_BASKET = 'ADD_ITEM_INTO_BASKET';
export const REMOVE_ITEM_INTO_BASKET = 'REMOVE_ITEM_INTO_BASKET';
export const INITIAL_BASKET = 'INITIAL_BASKET';
export const RESET_BASKET = 'RESET_BASKET';
export const RESET_ERRORS = 'RESET_ERRORS';
export const EDIT_OWNER = 'EDIT_OWNER';
export const CHANGE_QUERY_TEXT = 'CHANGE_QUERY_TEXT';

// Async
export const FETCH_ITEMS = 'FETCH_ITEMS';
export const FETCH_MORE_ITEMS = 'FETCH_MORE_ITEMS';
export const MAKE_ORDER = 'MAKE_ORDER';
export const FETCH_TOP_SALES = 'FETCH_TOP_SALES';
export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
